# Read about factories at http://github.com/thoughtbot/factory_girl

FactoryGirl.define do
  # TODO replace these with autogenerated values
  factory :checkin do
      lat "51.502557"
      lon "-0.07253941"
      timestamp "1306396092"
      foursquare_id "4dde05bc1f6e0369473a10fa"
      timezone "Europe/London"
    end
end